sudo: required
dist: trusty

language: cpp

cache:
  apt: true

addons:
  apt:
    sources:
    - boost-latest
    packages:
    - libboost1.55-all-dev
    - clang-3.6

compiler:
  - clang
install:
  - cd src/ && make
  - cd ../tests/ && make

script:
  - ./test_quantumAnnealing.out