sudo: required
dist: trusty

language: cpp

cache:
  apt: true

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - libboost1.55-all-dev
    - clang-3.6
    - gcc-5
    - g++-5

compiler:
  - clang

install:
  - cd src/ && make
  - cd ../test/ && make

script:
  - pwd
  - test/test_quantumAnnealing.out

