# Author Johann Fredrik Jadebeck
#
# Simple Makefile for quantumAnnealing.cpp
runQuantumAnnealing: quantumAnnealing.cpp quantumMechanics.cpp runQuantumAnnealing.cpp
	g++ -o runQuantumAnnealing runQuantumAnnealing.cpp quantumAnnealing.cpp quantumMechanics.cpp -I /usr/include/eigen3/ -std=c++11 -O3 -w
