# Author Johann Fredrik Jadebeck
#
# Simple Makefile for quantumAnnealing.cpp
quantumAnnealing: quantumAnnealing.cpp
	g++ -o quantumAnnealing quantumAnnealing.cpp -I /usr/include/eigen3/ -std=c++11 -O3 -w
