# Author Johann Fredrik Jadebeck
#
# Simple Makefile for quantumAnnealing.cpp

runQuantumAnnealing: quantumAnnealing.cpp runQuantumAnnealing.cpp
	g++ -o runQuantumAnnealing.out runQuantumAnnealing.cpp quantumAnnealing.cpp -I ../lib/eigen/ -std=gnu++11 -O3 -w
